In [1]:
import numpy as np
from scipy.stats import chi2_contingency

# Confusion Matrix untuk masing-masing model
confusion_matrices = {
    'Tanpa Normalisasi': np.array([[75, 24], [18, 37]]),   # TN, FP, FN, TP
    'Min-Max Scaling': np.array([[84, 15], [14, 41]]),
    'Z-Score (Standard Scaling)': np.array([[83, 16], [16, 39]]),
    'Decimal Scaling': np.array([[77, 22], [19, 36]])
}

# Melakukan uji chi-square untuk setiap confusion matrix
for model, cm in confusion_matrices.items():
    chi2, p, dof, expected = chi2_contingency(cm)
    print(f"Metode Normalisasi: {model}")
    print(f"Chi-Square: {chi2:.4f}")
    print(f"P-value: {p:.4f}")
    print(f"Degrees of Freedom: {dof}")
    print(f"Expected Frequencies: \n{expected}")
    print("\n" + "-"*50)


Metode Normalisasi: Tanpa Normalisasi
Chi-Square: 25.5994
P-value: 0.0000
Degrees of Freedom: 1
Expected Frequencies: 
[[59.78571429 39.21428571]
 [33.21428571 21.78571429]]

--------------------------------------------------
Metode Normalisasi: Min-Max Scaling
Chi-Square: 51.3639
P-value: 0.0000
Degrees of Freedom: 1
Expected Frequencies: 
[[63. 36.]
 [35. 20.]]

--------------------------------------------------
Metode Normalisasi: Z-Score (Standard Scaling)
Chi-Square: 43.8044
P-value: 0.0000
Degrees of Freedom: 1
Expected Frequencies: 
[[63.64285714 35.35714286]
 [35.35714286 19.64285714]]

--------------------------------------------------
Metode Normalisasi: Decimal Scaling
Chi-Square: 26.3360
P-value: 0.0000
Degrees of Freedom: 1
Expected Frequencies: 
[[61.71428571 37.28571429]
 [34.28571429 20.71428571]]

--------------------------------------------------


In [2]:
import numpy as np
from scipy.stats import chi2_contingency

# Confusion Matrix untuk masing-masing model
confusion_matrices = {
    'Tanpa Normalisasi': np.array([[75, 24], [18, 37]]),   # TN, FP, FN, TP
    'Min-Max Scaling': np.array([[84, 15], [14, 41]]),
    'Z-Score (Standard Scaling)': np.array([[83, 16], [16, 39]]),
    'Decimal Scaling': np.array([[77, 22], [19, 36]])
}

# Mengambil confusion matrix untuk Tanpa Normalisasi
cm_no_normalization = confusion_matrices['Tanpa Normalisasi']

# Melakukan uji chi-square untuk perbandingan dengan model Tanpa Normalisasi
for model, cm in confusion_matrices.items():
    if model != 'Tanpa Normalisasi':  # Membandingkan dengan model lain
        chi2, p, dof, expected = chi2_contingency([cm_no_normalization, cm])
        print(f"Perbandingan: Tanpa Normalisasi vs {model}")
        print(f"Chi-Square: {chi2:.4f}")
        print(f"P-value: {p:.4f}")
        print(f"Degrees of Freedom: {dof}")
        print(f"Expected Frequencies: \n{expected}")
        print("\n" + "-"*50)


Perbandingan: Tanpa Normalisasi vs Min-Max Scaling
Chi-Square: 81.0831
P-value: 0.0000
Degrees of Freedom: 4
Expected Frequencies: 
[[[61.39285714 37.60714286]
  [34.10714286 20.89285714]]

 [[61.39285714 37.60714286]
  [34.10714286 20.89285714]]]

--------------------------------------------------
Perbandingan: Tanpa Normalisasi vs Z-Score (Standard Scaling)
Chi-Square: 73.5212
P-value: 0.0000
Degrees of Freedom: 4
Expected Frequencies: 
[[[61.71428571 37.28571429]
  [34.28571429 20.71428571]]

 [[61.71428571 37.28571429]
  [34.28571429 20.71428571]]]

--------------------------------------------------
Perbandingan: Tanpa Normalisasi vs Decimal Scaling
Chi-Square: 55.6098
P-value: 0.0000
Degrees of Freedom: 4
Expected Frequencies: 
[[[60.75 38.25]
  [33.75 21.25]]

 [[60.75 38.25]
  [33.75 21.25]]]

--------------------------------------------------
